### ISSUE TITLE
column table does not touch unlearner on MIX

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#100]
The cluster has 2 servers and is configured with unleaner enabled (max_size = 3).
Now think of the following scenario:

1. Train Server 1 with 3 rows: [user1, user2, user3]
2. Train Server 2 with 3 rows: [user4, user5, user6]
3. do_mix

Then both servers have 6 rows: [user1, user2, user3, user4, user5, user6]

`mixable_versioned_table` should touch the unlearner when adding new rows.

**Comment by kmaehashi** [comment]
This issue was confirmed using NN-based recommender.
May affect NN-based classifier and anomaly too.

**Comment by gintenlabo** [comment]
fixed via https://github.com/jubatus/jubatus_core/issues/113.
