### ISSUE TITLE
Drivers should be thread safe.

### ISSUE THREAD

**Issue by kumagi** [jubatus/jubatus_core#112]
for concurrency of machine learning, Jubatus server holds giant lock for each model.
But giant lock is harmful for performance on multi-core processors.

Drivers should be thread safe, and server should not hold giant lock for each model.

**Comment by kmaehashi** [comment]
:+1:

This change will make core layer work more efficient especially in cases that feature extraction phase (which can be done simultaneously) is heavy.

**Comment by kmaehashi** [comment]
We'll make classifier driver thread-safe in 0.1.2 & 0.2.0.
Let's discuss what engine to make thread-safe for next.

**Comment by kmaehashi** [comment]
We've made classifier thread-safe.
I'll separate this issue.
