### ISSUE TITLE
jubabandit: trial_count should be incremented when arm selection

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#125]
Several bandit algorithms currently increment trial_count when reward is registered.
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/bandit/summation_storage.cpp#L67

trial_count should be incremented when an arm is selected.

**Comment by gintenlabo** [comment]
Not several, but ALL. It's expected behavior as it stands now.
I think it's better to add option if you want to increment `trial_count` when arms selected, not rewards are registered.

**Comment by kmaehashi** [comment]
Fixed via #133.
