### ISSUE TITLE
bandit: Several calculations in exp3 look wrong.

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#157]
These two calculations below look wrong.
1. https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/bandit/exp3.cpp#L56
2. https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/bandit/exp3.cpp#L92

1. should be  ``weights[i] = (1.0 - gamma_) * weights[i] / total_weight + gamma_ / n``
2. should be ``reward / weights[i] * gamma_ / arms.size())``

**Comment by kmaehashi** [comment]
Fixed via #158
