### ISSUE TITLE
bandit: ucb1 always select the same arm when assume rewarded is true

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#159]
ucb1 doesn't increment the trial_count when the arm is chosen because trial_count is zero.
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/bandit/ucb1.cpp#L45

Therefore ucb1 always select the same arm when assume rewarded option is true.

**Comment by kmaehashi** [comment]
Fixed via #160
