### ISSUE TITLE
unlearner: error message of unlearner can be improved

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#178]
Currently, when number of sticky IDs reached the upper limit of the unlearner, `no more space available to add new ID/row: ${ID}` error message will be returned to the client.  This message is a bit difficult to understand as the message does not mention `unelarner`.
This message is used in 5 different locations: https://github.com/jubatus/jubatus_core/search?utf8=%E2%9C%93&q=%22no+more+space+available%22&type=Code

How about changing it to `cannot add new ID/row as number of sticky IDs reached the maximum size of unlearner: ${ID}`

**Comment by rimms** [comment]
Fixed via #178
