### ISSUE TITLE
clustering: Throw exception when get_k_center/get_core_members is called before clustering is performed

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#185]
``clustering::get_nearest_center`` raises an exception when called before clustering is performed. (See. https://github.com/jubatus/jubatus_core/issues/150 and https://github.com/jubatus/jubatus_core/pull/95)

But, ``clustering::get_k_center`` and ``clustering::get_core_members`` does not raise an exception in the same situation. (empty list will be returned)

It's confusing.

I think ``clustering::get_k_center`` and ``clustering::get_core_members`` should raise an exception when called before clustering is performed.

**Comment by kmaehashi** [comment]
Fixed via #207
