### ISSUE TITLE
bandit: ucb1's select_arm is slowly than other algorithm

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#186]
``ucb1``'s ``select_arm`` is the slowest of all (``ucb1``, ``exp3``, ``softmax``, ``epsilon_greedy``).

algorithm      | QPS
---------------|----
epsilon_greedy | 107,128
exp3           | 95,740
softmax        | 95,840
ucb1           | 36,695

The reason is the follows: 
* ``ucb1`` will scan all of arm_id **twice**. (Other algorithm will scan once)
  * https://github.com/jubatus/jubatus_core/blob/0.2.2/jubatus/core/bandit/ucb1.cpp#L42-L49
  * https://github.com/jubatus/jubatus_core/blob/0.2.2/jubatus/core/bandit/ucb1.cpp#L54-L62

I guess that this implementation can be improved.

**Comment by TkrUdagawa** [comment]
I added total_trial_count to summation storage and removed a for loop of ucb1's select_arm.

I got a benchmark result of select_arm using 100 arms. 
Before:  17667 QPS
After: 36330 QPS

Its performance nearly doubled in this setting.

**Comment by TkrUdagawa** [comment]
fixed via #214
