### ISSUE TITLE
Implement get_staus of NN-based classifier

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#204]
``get_status`` is not implimented in NN-based classifier.
https://github.com/jubatus/jubatus_core/blob/0.2.4/jubatus/core/classifier/nearest_neighbor_classifier.cpp#L203-L206

I want to get the following values via ``get_status``:
* Number of record in the model
* Number of record of each label

**Comment by kmaehashi** [comment]
> Number of record of each label

I think this feature is also needed for linear classifiers, how do you think?
My idea is to return counts via `get_labels` API.

**Comment by rimms** [comment]
> I think this feature is also needed for linear classifiers, how do you think?

That's right!

> My idea is to return counts via get_labels API.

I agree with you. :+1:

**Comment by rimms** [comment]
Fixed via #272 and #278
