### ISSUE TITLE
Classifier: get_labels of NN does not return mixed labels

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#210]
``labels_`` is not mixed.
https://github.com/jubatus/jubatus_core/blob/0.2.5/jubatus/core/classifier/nearest_neighbor_classifier.hpp#L74

**Comment by kmaehashi** [comment]
There are some possible solutions:

1. Mix labels (send all labels in every MIX session)
1. Mix labels (only MIX diff area in MIX session)
1. Generate labels from mixed NN model

Ideas need to be compared by view points including implementation costs and protocol compatibility

**Comment by rimms** [comment]
fixed via #271
