### ISSUE TITLE
Classifier: delete_label, set_label of NN should be take a lock for labels

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#213]
``labels_`` is not protected by the lock.

https://github.com/jubatus/jubatus_core/blob/0.2.5/jubatus/core/classifier/nearest_neighbor_classifier.hpp#L74
https://github.com/jubatus/jubatus_core/blob/0.2.5/jubatus/core/classifier/nearest_neighbor_classifier.cpp#L151
https://github.com/jubatus/jubatus_core/blob/0.2.5/jubatus/core/classifier/nearest_neighbor_classifier.cpp#L180

**Comment by kmaehashi** [comment]
Fixed via #221
