### ISSUE TITLE
combination_rules#except_{left, right} does not work

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#232]
https://github.com/jubatus/jubatus_core/blob/0.2.7/jubatus/core/fv_converter/converter_config.cpp#L347-L348

Above codes should be followings:
```CPP
matcher_ptr m_left(create_key_matcher(rule.key_left, rule.except_left));
matcher_ptr m_right(create_key_matcher(rule.key_right, rule.except_right));
```

**Comment by shiodat** [comment]
Add combination_rules test and 'build' finished successfully.
https://github.com/jubatus/jubatus_core/commit/fc669d9c5316630f0c82aa4cca84264d220f2bcc

**Comment by shiodat** [comment]
#258

**Comment by rimms** [comment]
Fixed via https://github.com/jubatus/jubatus_core/pull/258
