### ISSUE TITLE
set value to tbl_ twice

### ISSUE THREAD

**Issue by yukimori** [jubatus/jubatus_core#233]
On local_storage::set sets value to tbl_twice

In local_storage::set use local_storage::set_nolock which sets value to tbl_.
And then, local_storage set same value to tbl_ again.

https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/storage/local_storage.cpp#L134-L135

**Comment by kumagi** [comment]
(As a author of that line) below line should be removed.

**Comment by kmaehashi** [comment]
Fixed via #236
