### ISSUE TITLE
Support inverted index in NN classifier

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#234]
I think it would be better NN classifier can use inverted index method because it is an accurate and parameter free method. 

Currently, there are two options:
1. Modify NN classifier to supports Recommender
2. Implement an inverted index method in NearestNeighbor

**Comment by TkrUdagawa** [comment]
We decided to modify NN classifier to support Recommender method in 2016-02-15's meeting.

**Comment by kmaehashi** [comment]
Discussion sidenotes:

> 2. Implement an inverted index method in NearestNeighbor

To implement this we should drastically modify column_table data structure, because current `column_table`:

* only supports 1- or 2-column table
* records owners (versions) as per-row basis, i.e., MIX is performend per row.

So this too hard way to go.

**Comment by kazuki** [comment]
こんな感じにNNに直接組み込むのはだめなのでしょうか？
https://github.com/kazuki/jubatus_core/tree/wip/nn_inverted_index
(da347be3a78fe88098cd4f63fde111c1bdbacf6c でNNのクラス抽象化構造を変更し， a22b29028245dacb434724ca04a3ef5be5f53635 でInvertedIndexを移植しています)

MIXとなの都合もあるので，上の実装が正しく動くのかは分かりませんが
とりあえずjubatus_core単体では動作しています．

以下の点を気にしています
* ClassifierからNNを利用する場合はorig_は不要な気がするので，メモリを節約したい
(idから探索したい場合はオプションでorig_を確保するような形に...)
* NNからRecommenderを利用できたりRecommenderからNNを利用できたり循環が発生するのが...

#265 を作成する際に思ったのですが，NNとRecommenderでコード重複が多いので
https://github.com/kazuki/jubatus_core/commits/wip/recommender_refactoring では
Recommenderにしか無いアルゴリズムをNNに移植して，RecommenderからはNN以外を削除するようにしてみたのですが，こっちは他への影響が大きいので，とりあえずはNNに直接InvertedIndexを組み込んでしまうのが良いのではないかと思いました．

**Comment by TkrUdagawa** [comment]
From discussion on 11th April, we concluded that implementing inverted index method under Classifier will be the most reasonable solution.
That is because:
- As @k_oi mentioned, using Recommender behind Classifier requires much memory which is useless for Classifier functions. 
- If inverted index is implemented in Nearest Neighbor, behavior of `set_row` API will vary according to method (inverted index: insert, other method: overwrite) and it will be very confusing for users.  In addition, it is difficult to support `similar_row_from_id` and `neighbor_row_from_id` APIs. 
- Implementing inverted index under Classifier doesn't have any effect on existing functions and make unnecessary confusion. This solution also doesn't use extra memory.

**Comment by kmaehashi** [comment]
Implemented in #276.
