### ISSUE TITLE
Burst : burst weight becomes inf without error messages

### ISSUE THREAD

**Issue by imaimai1125** [jubatus/jubatus_core#241]
When  R/D*s >1 (s is the scaling parameter), burst weight becomes infinity.
R : the number of documents in which keyword is included within certain window size
D : the number of all documents within certain window size

However, no error messages are shown.
I want to show error messages when this problem occurs.

**Comment by kmaehashi** [comment]
Discussion in the meeting: we decided to document this behavior to website.
Unlike ``inf`` in Classifier model (which is a unrecoverable situation),

* ``inf`` in burst score is intentionally set to notify the user of this situation:  https://github.com/jubatus/jubatus_core/blob/0.3.3/jubatus/core/burst/engine.cpp#L194-L203
* it can also be treated as a kind of transitional state and may go back to non-inf value (if ``D`` increase or next window is created)

**Comment by kmaehashi** [comment]
Fixed via https://github.com/jubatus/website/pull/289
