### ISSUE TITLE
Classifier: NN (based classifer) is lower performance

### ISSUE THREAD

**Issue by yukimori** [jubatus/jubatus_core#244]
To improve NN perfomance, we modify NN to culculate hash with multi threads.

**Comment by kmaehashi** [comment]
Merge order:

```
#246 => #250 ==> #260 => #247
        #254 =^
```

**Comment by kazuki** [comment]
念の為の補足ですが #260 の2016/04/04の更新により，#254 は不要となりましたので，
#254 はマージ順序には特に関与しません．

**Comment by kmaehashi** [comment]
@kazuki 補足ありがとうございます。C++11対応(#254)は#260のブロッキングでない旨、了解です。

**Comment by kmaehashi** [comment]
Fixed via PRs above.
