### ISSUE TITLE
split string feature by specified separator

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#255]
Extracting a string feature by specified separator (like ",") is one of the common requirement.
Currently only `space_splitter`, which splits by white space, is provided, but I am happy if other separator can be specified.

**Comment by ytobe** [comment]
この対応における変更内容は以下の通りの方針とします：

設定ファイルのstring_typesに新規のmethodとして"split" 、
またsplitについて、区切り文字を示すパラメータとしてseparatorを追加する方針とします。
> "string_types": {
>  "comma_split": {"method": "split" , "separator":"," }
> }

この定義を使用したstring_rulesは下記のようになります。(既存と変わりはありません。)
> { "key": "user/name", "type": "comma_split", "sample_weight": "bin", "global_weight": "bin" },

また、任意の文字で分割できるchar_splitterクラスを追加します。

**Comment by kmaehashi** [comment]
2016-06-13 定例での議論:

* `char_splitter` は、 `"separators"` に指定された **いずれかの** 各文字のシーケンスで分割する splitter とする。
  例えば、 `",:"` と指定した場合は、正規表現 `/[,:]+/` で split することに相当する。
* 複数の文字を split するため、設定パラメタ名は `"separator"` ではなく `"separators"` とするのが良い。

**Comment by kmaehashi** [comment]
実装後にドキュメントの更新もお願いします。

* http://jubat.us/en/fv_convert.html#string-rules
* http://jubat.us/ja/fv_convert.html#string-rules

**Comment by kmaehashi** [comment]
Fixed via #294
