### ISSUE TITLE
Recommender: inverted_index does not return similar ids when using empty data

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#274]
When using empty data:
* ``lsh``: retrun ids
* ``minhash``: retrun ids
* ``euclid_lsh``: retrun ids
* ``inverted_index``: return empty list
* ``inverted_index_euclid``: return ids

It's confusing.

(refs. https://github.com/jubatus/jubatus_core/pull/273)

**Comment by kmaehashi** [comment]
I think `inverted_index` behavior is by design, as cosine similarity to empty vector (zero sfv) is undefined.

**Comment by rimms** [comment]
@kmaehashi Thanks for the follow-up. I understood this design.

But when using ``similar_row_from_id`` with unregistered id, result is not unified by algorithm. It’s confusing.

* ``lsh``: retrun ids
* ``minhash``: retrun ids
* ``euclid_lsh``: return empty list
* ``inverted_index``: return empty list
* ``inverted_index_euclid``: return ids

I will close this issue and raise new issue.
