### ISSUE TITLE
Recommender: similar_row_from_id behaves differently by algorithm  

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#275]
(In current develop branch)

When using `similar_row_from_id` with unregistered id:
- `lsh`: retrun ids
- `minhash`: retrun ids
- `euclid_lsh`: return empty list
- `inverted_index`: return empty list
- `inverted_index_euclid`: return ids

I think its should return empty list.

Note that my test scenario is the followings:
1. Start `jubarecoxmmender` with default config (`$JUBATUS_HOME/share/jubatus/example/config/recommender`)
2. `update_row(“user-01”, datum{“str_key1”: “str”, “num_key”: 1.0})`
3. `similar_row_from_id(“user-02”)`

(refs. #273, #274)

**Comment by kmaehashi** [comment]
:+1:
If the ID is missing in *model* (not *orig_*), we should return an empty list.

**Comment by rimms** [comment]
Added tests via #395
