### ISSUE TITLE
NearestNeighbor: euclid_lsh is low performance when executing {similar, neighbor}_row_from_{id, datum} in parallel.

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#279]
``euclid_lsh::neighbor_row_from_hash`` acquires and releases the lock too many times.
Its number is the same as the number of records.

- https://github.com/jubatus/jubatus_core/blob/0.2.9/jubatus/core/nearest_neighbor/euclid_lsh.cpp#L152
- https://github.com/jubatus/jubatus_core/blob/0.2.9/jubatus/core/storage/column_table.hpp#L206-L209

When excuting ``{similar, neighbor}_row_from_{id, datum}`` in parallel, the lock wait occurs a lot. (system-call occurs a lot.)
This causes the high cpu-load situation and low performance.

**Comment by kazuki** [comment]
fixed in current develop branch ? ( modified in #260 )
https://github.com/jubatus/jubatus_core/blob/develop/jubatus/core/nearest_neighbor/euclid_lsh.cpp#L175

**Comment by rimms** [comment]
@kazuki Thank you for the follow up. I will close this issue. 👍
