### ISSUE TITLE
Cannot build with Ubuntu 16.04

### ISSUE THREAD

**Issue by kazuki** [jubatus/jubatus_core#282]
ubuntu bug tracking issue
https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899
(related: #269)

build log ( https://travis-ci.org/jubatus/jubatus_core/jobs/123305141 )

```
[356/594] cxxprogram: build/jubatus/core/common/exception_test.cpp.2.o build/.unittest-gtest/gtest-1.7.0/fused-src/gtest/gtest-all.cc.3.o build/.unittest-gtest/gtest-1.7.0/fused-src/gtest/gtest_main.cc.3.o -> build/jubatus/core/common/exception_test
/usr/bin/ld: /root/build/jubatus/core/common/exception_test: hidden symbol `__cpu_indicator_init' in /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a(cpuinfo.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

**Comment by kmaehashi** [comment]
So far I propose adding configure option like `--disable-fmv` (disables `JUBATUS_USE_FMV`) to make it work on Ubuntu 16.04

**Comment by kazuki** [comment]
個人的にはAVX2の恩恵を受けたいので，Ubuntuのバグチケットに記載されている回避策(リンカオプションに -lgcc_s -lgcc を付与する)が良いと考えています．

ですが，Ubuntu 16.04は公式サポート外ですし，ソースからビルドする場合は簡単に回避できるので，
取り敢えずは様子見でいいかなと思ってます (Ubuntu側が対応するかもしれませんので，このバグチケットは備忘録代わりに立てました)．

なお，Ubuntu 16.04は #281 の影響を受けません．

**Comment by kazuki** [comment]
1年近く経ちましたが現在のUbuntuでもこの問題は治っていないようですので，
#281 とあわせて，すこし調査してみます https://github.com/kazuki/jubatus_core_buildtest

**Comment by kmaehashi** [comment]
Fixed via #345

**Comment by kmaehashi** [comment]
@lena2813 The fix for this issue now got merged. We are going to support Ubuntu 16.04 in the next release planned at the end of February.
