### ISSUE TITLE
NearestNeighbor: euclid_lsh should acquire exclusive lock when excuting {similar, neighbor}_row_from_{id, datum}

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#283]
We should acquire a read-lock before calling ``neighbor_row_from_hash`` .

FYI:
``minhash`` and ``lsh`` acquire a read-lock.
- https://github.com/jubatus/jubatus_core/blob/0.3.0/jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.cpp#L74
- https://github.com/jubatus/jubatus_core/blob/0.3.0/jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.cpp#L85

**Comment by kmaehashi** [comment]
Fixed via #285
