### ISSUE TITLE
Recommender: ignore distance calculation when the pair doesn't have any same key

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#305]
I've got a use case of inverted_index_euclid when a pair doesn't have any same key, it is better not to calculate the similarity because of both of analysis precision and performance.

---
Example:
Below data is registered in a Recommender:
 bird_A: `{"wing": 4, "claw": 3}`
 bird_B: `{"wing": 6, "claw": 2}`
 fish_A: `{"gill":15}`

Then, when data `{"gill":2}` is queried, the euclidean distance will be below
bird_A = sqrt((2-0)^2 + (0 -4)^2 + (0-3)^2) ≒ 5.39
bird_B = sqrt((2-0)^2 + (0 -6)^2 + (0-2)^2) ≒ 6.63
fish_A = sqrt((2 - 15)^2) = 13

In this case, bird_A is the closest to the query according to the distance. 
However we can doubt the query is really a bird because it doesn't have none of wing and claw.
In addition,  different from inverted_index, it is necessary to calculate the distance between all data points in inverted_index_euclid and this is very heavy when data set is huge.
For those reasons, calculating the distance between only fish_A, which has "gill", can lead to better results.

---

I want a option to realize this.

**Comment by kmaehashi** [comment]
:+1: I understand that such distance metrics (*chimera* of cosine and euclidean distance) may be expected in real world use-cases.

What will be returned in `similar_row_from_datum({"claw": 1})` case?

- Idea 1: only use the intersection of two feature vectors (e.g., distance will be calculated as if `bird_A == {"claw": 3}`)
- Idea 2: same result as the current implementation

> In addition, different from inverted_index, it is necessary to calculate the distance between all data points in inverted_index_euclid and this is very heavy when data set is huge.

Ah, I didn't notice that inverted_index omits IDs with score 0 from result.
I think this will become an another issue when using Anomaly with `inverted_index` backend.

**Comment by TkrUdagawa** [comment]
In other words, idea 1 reduces the dimension of feature vectors and calculates the distance in another space, while idea 2 complements missing values by 0 and calculates the distance in the same space as original feature vectors.

I think it depends on the situation what distance to be calculated.
In my opinion, inverted index euclid is suitable for denser numerical tasks and, in those cases, reducing dimension unintentionally  can be harmful.
Therefore I agree to Idea 2.

**Comment by kmaehashi** [comment]
Fixed via #309
