### ISSUE TITLE
Unlearner in Classifier should be protected by mutex

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#311]
https://github.com/jubatus/jubatus_core/blob/0.3.3/jubatus/core/classifier/nearest_neighbor_classifier.cpp#L160
https://github.com/jubatus/jubatus_core/blob/0.3.3/jubatus/core/classifier/nearest_neighbor_classifier.cpp#L171

Refs. #303

**Comment by rimms** [comment]
I changed the title. Because this problem exists in Linear-Classifier.

**Comment by kmaehashi** [comment]
Fixed via #343
