### ISSUE TITLE
Remove unused revert function

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#315]
There are two implementations of ``revert_feature`` function that reverts ``sfv_t`` into ``datum``.

* https://github.com/jubatus/jubatus_core/blob/0.3.3/jubatus/core/fv_converter/datum_to_fv_converter.cpp#L309-L339
* https://github.com/jubatus/jubatus_core/blob/0.3.3/jubatus/core/fv_converter/revert.cpp

The former one has a bug, has no tests, and is currently unused. Let's remove it to avoid confusion.

**Comment by TkrUdagawa** [comment]
fixed via #331
