### ISSUE TITLE
Hard to know which data cluster includes in Jubaclustering

### ISSUE THREAD

**Issue by yukimori** [jubatus/jubatus_core#317]
It is difficult to know which data includes cluster in Jubaclustering, because response data(= datum) does not have any information to identify indivisual data.

I think it is better to refactor Clustering API .

## add data structure
```
indexed_point 
  0: string  ID,
  1: datum point
```
ID indentify indivisual data. 

```
weighted_index
 0: double weight
 1: string ID
```

## modify API
```
bool push(0: list<indexed_point> points)
```
## add API
```
list<list<weighted_index>> get_core_members_light()
```
This API returns only IDs and Weights. It is easy to know which data includes cluster.

**Comment by kmaehashi** [comment]
Fixed via #326
