### ISSUE TITLE
Regression: unnecessary argument in the driver

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#319]
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/driver/regression.cpp#L40
Is ``model_storage`` necessary?
I think this code was forgotten to be deleted in [this commit](https://github.com/jubatus/jubatus_core/commit/15f1ea6ef2bed9b11215b314cb43658a93902ca6).

**Comment by kmaehashi** [comment]
Fixed via PRs above.
