### ISSUE TITLE
anomaly: ignore_kth_same_point may not work by inverted index euclid

### ISSUE THREAD

**Issue by imaimai1125** [jubatus/jubatus_core#348]
When using anomaly with `inverted_index_euclid`,  anomaly score sometimes becomes `inf`.
I think it may be solved to set threshold option when using `ignore_kth_same_point`, which is discussed before. (ref : https://github.com/jubatus/jubatus_core/issues/253)

> 2. Fix the Anomaly layer: if the distance between two points is under threshold (like 0.001), treat them as the same points, so that they can be filtered out

**Comment by yukimori** [comment]
steps to reproduce:
https://gist.github.com/imaimai1125/58831e36cd61ecd849ca80d1c5e2d75f

**Comment by imaimai1125** [comment]
I wrote the reason why lof score becomes inf here (in Japanese)
https://gist.github.com/imaimai1125/69c12c3a590e7c8dad9a2299d0bc16b8
I also listed some solutions, however, they all have both good and bad points.
I wanna discuss how to deal with this problem.

**Comment by imaimai1125** [comment]
In offline discussion, we have decided to fix this by following.

- If `sum_reachability` becomes 0 on the way to calculating `lrd`, add a small value to this.

**Comment by kmaehashi** [comment]
Fixed via #358
