### ISSUE TITLE
Add distance weight option to nearest neighbor regression

### ISSUE THREAD

**Issue by shiodat** [jubatus/jubatus_core#351]
Current nearest neighbor regression calculate the prediction value as follows:

1. Search k neighbor points of `x`, e.g. `{x_i | i = 1,2,...,k}`.
2. Calculate average of the neighbor target values and return it as prediction value,
    e.g.  `f(x) = sum_{i=1}^k f(x_i)`.

The method does not consider the distance between the given point `x` and each neighbor points `{x_i | i = 1,2,...,k}` to calculate the predicion value.
Therefore, I want to add distance weight option to nearest neighbor regression.

For example, in case we have a following neighbor table and want to predict  `f(x=5)`,
- Current average method will returns `f(x=5) = (10+20+30) / 3 = 20`.
- Distance weight average method will returns `f(x=5) ≈ (10+20+0) / 3 = 15`.

| Neighbor Rank | x | f(x) | d | w = 1/d | wf(x) | wf(x)/sum(w) |
|----------|------|----|-----|-------|-------|------------|
| 1 | 0 | 10 | 5 | 1/5 | 2 | ≈10 |
| 2 | 10 | 20 | 5 | 1/5 | 4 | ≈20 |
| 3 | 1000 | 30 | 995 | 1/995 | 6/199 | ≈0 |

If we add distance weight option, I propose to change the configulation files as follows:
```
{
    "method": "NN",
    "parameter": {
        "method": "euclid_lsh",
        "nearest_neighbor_num": 8,
        "weight": "distance" or "uniform",
        "parameter": {
            "hash_num": 512
        }
    }
}
```

**Comment by kmaehashi** [comment]
Discussion on 2017-03-06:
* The new config parameter `weight` is optional.  When omitted, it behaves the same way as the previous version (i.e., `"uniform"``).

**Comment by kmaehashi** [comment]
Implemented via PRs above.
