### ISSUE TITLE
bandit: Add epsilon-decreasing option

### ISSUE THREAD

**Issue by imaimai1125** [jubatus/jubatus_core#354]
A fixed epsilon, the constant factor in a simple epsilon-greedy strategy, prevents the strategy from getting arbitrarily close to the optimal lever. 

To solve this problem, some paper suggest natural variant of epsilon-greedy strategy, which is called "epsilon-decreasing strategy". ([Ref1(Auer et al.)](https://homes.di.unimi.it/~cesabian/Pubblicazioni/ml-02.pdf), [Ref2(Vermorel et al.)](http://www.cs.nyu.edu/~mohri/pub/bandit.pdf))

It may be good to add an option of `decreasing epsilon` to the epsilon-greedy method.

**Comment by kmaehashi** [comment]
Implemented via PRs above.
