### ISSUE TITLE
anomaly: bulk insert API

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#360]
Currently anomaly does not provide ways to bulk insert records.

Currently `add` API inserts a record as follows:

1. Inserts a datum to NN backend
2. Updates LRD / kdist of its neighbors (heavy!)
3. Calculate LOF score for the datum

If we have multiple records, we should call `add` API for each record; as a result, it is time consuming, mainly due to the computation cost of LRD / kdist.

It is better if API like `add_bulk`, which accepts multiple records at once and behaves as follows:

1. Bulk-inserts **each** datum to NN backend
2. Bulk-updates LRD / kdist of its neighbors (which is still heavy, but much better than calling `add` for multiple times)
3. **Do not** calculate LOF score; returns nothing, as we rarely need LOF scores when adding data.

**Comment by rimms** [comment]
Fixed via #391 and https://github.com/jubatus/jubatus/pull/1220
