### ISSUE TITLE
SSE2 test doing nothing?

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#374]
https://github.com/jubatus/jubatus_core/blob/1.0.3/wscript#L120-L122

```
  if not func_multiver_enabled:
    sse2_test_code = '#ifdef __SSE2__\nint main() {}\n#else\n#error\n#endif'
    conf.check_cxx(fragment=sse2_test_code, msg='Checking for sse2', mandatory=False)
```

It seems that it has not effect. @kazuki

**Comment by kazuki** [comment]
\_\_SSE2\_\_ is defined only sse2 supported architecture (like x86_64).

if configure on no sse2 architecture, \_\_SSE2\_\_ is not defined and goto \#error route.

**Comment by kmaehashi** [comment]
Exactly, so maybe ``mandatory=False`` should be removed?
I think currently it just slips.

**Comment by kazuki** [comment]
Main subject of this test is output a sse2 supporting status.

Implementation of lsh is three types.
* AVX2 vectorized code (FMV enabled)
* SSE2 vectorized code (FMV enabled or SSE2 enabled)
* non vectorized code (fallback. FMV enabled or SSE2 disabled)

If mandatory=False removed, jubatus_core cannot build on non x86_64 archtecture (like i386, emscripten-javascript).

**Comment by kmaehashi** [comment]
Thank you, it made things clear. I didn't know that it was just for informational purpose.
