### ISSUE TITLE
There are unused classes

### ISSUE THREAD

**Issue by kazuki** [jubatus/jubatus_core#375]
The following is part of unused classes.
```
jubatus/util/concurrent/chan.h
jubatus/util/concurrent/mvar.h
jubatus/util/concurrent/qsem.h
jubatus/util/data/string/aho_corasick.h
```
can remove?
or are there reason to keep?

**Comment by kmaehashi** [comment]
When importing pficommon to jubatus (https://github.com/jubatus/jubatus/pull/467), we excluded several components:

https://github.com/jubatus/jubatus_core/tree/master/jubatus/util

We didn't exclude files or classes/functions inside each component, as we thought such change may cause pain when backporting upstream changes in future.

So, we don't have positive reasons to remove them.

In addition, it is harmless, and someone using Jubatus Core may already using it (not very likely, though).

**Comment by kazuki** [comment]
thanks for reply.
