### ISSUE TITLE
nearest neighbor: neighbor_row with multi threads fails when data is empty

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#382]
When I executed neighbor_row to empty model using multi threads, floating exception occurred.
This is caused by 0 division when `size` is 0 like [here](https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/nearest_neighbor/bit_vector_ranking.hpp#L53-L56).

**Comment by kmaehashi** [comment]
Fixed via #383
