### ISSUE TITLE
anomaly_test doesn't run using python3

### ISSUE THREAD

**Issue by TkrUdagawa** [jubatus/jubatus_core#390]
In python3, `map` is evaluated lazily.
Therefore the code used in wscript of anomaly [here](https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/anomaly/wscript#L40) doesn't work correctly

**Comment by TkrUdagawa** [comment]
The similar codes are found in graph and recommender.
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/graph/wscript#L30
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/recommender/wscript#L39

**Comment by rimms** [comment]
Fixed via #390
