### ISSUE TITLE
Support unlearning for `inverted_index`

### ISSUE THREAD

**Issue by unnonouno** [jubatus/jubatus_core#51]
`inverted_index` is stable and easy to use. But, it doesn't support unlearning. Users who need unlearning cannot choose `inverted_index`.

I have two ideas to achieve it:

- implement `inverted_index` nearest neighbor module, and implement unlearning
- implement unlearning in `inverted_index` recommender

The former is preferable.

**Comment by kmaehashi** [comment]
Fixed via #120
