### ISSUE TITLE
"retain_projection" parameter in recommender euclid_lsh seems ineffective

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#98]
Even when `retain_projection` is set to `true`, it dynamically calculates projection vectors:

https://github.com/jubatus/jubatus_core/blob/0.0.7/jubatus/core/recommender/euclid_lsh.cpp#L60-L76

These seems a dead code; after removing these lines it compiles successfully.

https://github.com/jubatus/jubatus_core/blob/0.0.7/jubatus/core/recommender/euclid_lsh.cpp#L230-L257

**Comment by gwtnb** [comment]
According to @beam2d, the above statement is correct.
